### ISSUE TITLE
Doesn't Work 

### ISSUE THREAD

**Issue by Freddie0Mercury** [JetStream96/QSimPlanner#25]
System.DllNotFoundException: Unable to load DLL 'mozglue': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Gecko.Xpcom.Alloc(IntPtr size)
   at Gecko.nsAString..ctor() in D:\temp\339b193\Geckofx-Core\nsString.cs:line 883
   at Gecko.nsAString..ctor(String value) in D:\temp\339b193\Geckofx-Core\nsString.cs:line 895
   at Gecko.Xpcom.Initialize(String binDirectory) in D:\temp\339b193\Geckofx-Core\Xpcom.cs:line 324
   at QSP.UI.Views.MiscInfo.AirportMapControl.EnableBrowser() in C:\Data\Programming\Projects\QSimPlanner\Source Code\src\QSP\UI\Views\MiscInfo\AirportMapControl.cs:line 227
   at QSP.UI.Views.MiscInfo.AirportMapControl.set_BrowserEnabled(Boolean value) in C:\Data\Programming\Projects\QSimPlanner\Source Code\src\QSP\UI\Views\MiscInfo\AirportMapControl.cs:line 32
   at QSP.UI.Presenters.MiscInfo.MiscInfoPresenter..ctor(IMiscInfoView view, AirportManager airportList, Locator`1 windTableLocator, Boolean enableBrowser, Func`1 origGetter, Func`1 destGetter, Func`1 altnGetter) in C:\Data\Programming\Projects\QSimPlanner\Source Code\src\QSP\UI\Presenters\MiscInfo\MiscInfoPresenter.cs:line 28
   at QSP.UI.Forms.QspForm.InitMiscInfoMenu() in C:\Data\Programming\Projects\QSimPlanner\Source Code\src\QSP\UI\Forms\QspForm.cs:line 334
   at QSP.UI.Forms.QspForm.InitControls() in C:\Data\Programming\Projects\QSimPlanner\Source Code\src\QSP\UI\Forms\QspForm.cs:line 296
   at QSP.UI.Forms.QspForm.<Init>b__25_0() in C:\Data\Programming\Projects\QSimPlanner\Source Code\src\QSP\UI\Forms\QspForm.cs:line 102
   at QSP.UI.Forms.QspForm.ShowSplashWhile(Action action) in C:\Data\Programming\Projects\QSimPlanner\Source Code\src\QSP\UI\Forms\QspForm.cs:line 181
   at QSP.UI.Forms.QspForm.Init() in C:\Data\Programming\Projects\QSimPlanner\Source Code\src\QSP\UI\Forms\QspForm.cs:line 97
   at QSP.Program.Main(String[] args) in C:\Data\Programming\Projects\QSimPlanner\Source Code\src\QSP\Program.cs:line 83

I get this message when trying to open. Any idea?

**Comment by tombogle** [comment]
Based on this: https://stackoverflow.com/questions/45997649/geckofx-core-system-dllnotfoundexception, I'm guessing it is because of a missing Visual C++ redistributable.

**Comment by andyapilot** [comment]
this fix does not work, I really want use this software. I get the same error for the latest version.
